In [7]:
import numpy as np #Задание №1 

In [13]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
mean_a = a.mean(axis = 0)

In [14]:
print(mean_a)

[2.  8.4]


In [15]:
a_centered = a - mean_a #Задание №2 
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


[[-2.4]
 [-0.4]
 [ 2.6]
 [ 1.6]
 [-1.4]]


[[-1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [-1.]]


In [46]:
a = a_centered[0:, 1:2]*a_centered[0: , :1] #Задание №3
print(a)

[[ 2.4]
 [-0. ]
 [ 2.6]
 [ 1.6]
 [ 1.4]]


In [48]:
a_centered_sp = a.sum()
print(a_centered_sp) #Скалярное произведение столбцов

8.0


In [51]:
# количество наблюдений равно кол-ву строк, знач N(5)-1=4 

8.0


In [ ]:
# 8\4 = 2 - деление a_centered_sp на число наблюдений N-1